type Property @collection(name: "properties") {
  propertyId: String! @unique
  MFR_AdditionalLeaseRestrictions: String
  AdditionalParcelsYN: Boolean
  Appliances: String
  MFR_ApprovalProcess: String
  ArchitecturalStyle: String
  AssociationAmenities: String
  MFR_AssociationApprovalRequiredYN: String
  MFR_AssociationEmail: String
  AssociationFee: Float
  AssociationFeeFrequency: String
  AssociationFeeIncludes: String
  MFR_AssociationFeeRequirement: String
  MFR_AssociationURL: String
  AssociationYN: Boolean
  AttachedGarageYN: Boolean
  MFR_AvailableForLeaseYN: String
  BathroomsFull: Int
  BathroomsHalf: Int
  BathroomsTotalInteger: Int
  BedroomsTotal: Int
  MFR_BuildingNameNumber: String
  BuyerAgencyCompensation: String
  CarportYN: Boolean
  MFR_CDDYN: String
  City: String
  CoListAgentDirectPhone: String
  CoListAgentFullName: String
  CoListAgentMlsId: String
  CoListOfficeMlsId: String
  CoListOfficeName: String
  CommunityFeatures: String
  ConstructionMaterials: String
  Cooling: String
  Country: String
  CountyOrParish: String
  CumulativeDaysOnMarket: Int
  MFR_CurrentPrice: String
  DaysOnMarket: Int
  DirectionFaces: String
  Directions: String
  ElementarySchool: String
  MFR_EndDateofLease: String
  MFR_ExistLseTenantYN: String
  ExteriorFeatures: String
  FireplaceYN: Boolean
  MFR_FloodZoneCode: String
  Flooring: String
  FoundationDetails: String
  MFR_GarageDimensions: String
  GarageSpaces: Int
  GarageYN: Boolean
  MFR_GreenVerificationCount: String
  Heating: String
  HighSchool: String
  MFR_HomesteadYN: String
  InteriorFeatures: String
  InternetAddressDisplayYN: Boolean
  InternetConsumerCommentYN: Boolean
  InternetEntireListingDisplayYN: Boolean
  Latitude: Float
  Levels: String
  ListAgentAOR: String
  ListAgentDirectPhone: String
  ListAgentEmail: String
  ListAgentFullName: String
  ListAgentKey: String
  ListAgentMlsId: String
  ListAgentPager: String
  ListAOR: String
  ListingAgreement: String
  ListingContractDate: String
  ListingId: String
  ListingKey: String
  OriginatingSystemKey: String
  ListingTerms: String
  MFR_ListOfficeHeadOfficeKeyNumeric: String
  ListOfficeKey: String
  ListOfficeMlsId: String
  ListOfficeName: String
  ListOfficePhone: String
  ListPrice: Int
  LivingArea: Int
  MFR_LivingAreaMeters: String
  Longitude: Float
  LotFeatures: String
  LotSizeAcres: Float
  LotSizeSquareFeet: Int
  MFR_LotSizeSquareMeters: String
  MiddleOrJuniorSchool: String
  MFR_MinimumLease: String
  MLSAreaMajor: String
  MlsStatus: String
  OriginatingSystemModificationTimestamp: String
  MFR_MonthlyHOAAmount: String
  NewConstructionYN: Boolean
  MFR_NonRepCompensation: String
  OriginalEntryTimestamp: String
  OriginalListPrice: Int
  OriginatingSystemName: String
  ParcelNumber: String
  ParkingFeatures: String
  MFR_PetRestrictions: String
  PetsAllowed: String
  PhotosChangeTimestamp: String
  PhotosCount: Int
  PoolPrivateYN: Boolean
  PostalCode: String
  PostalCodePlus4: String
  PrivateRemarks: String
  PropertySubType: String
  PropertyType: String
  PublicRemarks: String
  MFR_PublicRemarksAgent: String
  PublicSurveyRange: String
  PublicSurveySection: String
  MFR_RealtorInfo: String
  Roof: String
  MFR_RoomCount: String
  MFR_SDEOYN: String
  SeniorCommunityYN: Boolean
  Sewer: String
  ShowingRequirements: String
  SpecialListingConditions: String
  StandardStatus: String
  StateOrProvince: String
  StatusChangeTimestamp: String
  StoriesTotal: Int
  StreetName: String
  StreetNumber: String
  StreetSuffix: String
  SubdivisionName: String
  TaxAnnualAmount: Float
  TaxBlock: String
  TaxBookNumber: String
  TaxLegalDescription: String
  TaxLot: String
  TaxYear: Int
  MFR_TotalAcreage: String
  MFR_TotalAnnualFees: String
  MFR_TotalMonthlyFees: String
  Township: String
  TransactionBrokerCompensation: String
  MFR_UniversalPropertyID: String
  UnparsedAddress: String
  Utilities: String
  View: String
  MFR_WaterAccessYN: String
  MFR_WaterExtrasYN: String
  MFR_WaterfrontFeetTotal: String
  WaterfrontYN: Boolean
  WaterSource: String
  MFR_WaterView: String
  MFR_WaterViewYN: String
  WindowFeatures: String
  YearBuilt: Int
  MFR_YrsOfOwnerPriorToLeasingReqYN: String
  Zoning: String
  RoomKitchenDimensions: String
  RoomKitchenFeatures: String
  MFR_room1_RoomFlooring: String
  RoomKitchenLength: Int
  RoomKitchenLevel: String
  RoomType: String
  RoomKitchenWidth: Int
  RoomMasterBedroomDimensions: String
  MFR_room2_RoomFlooring: String
  RoomMasterBedroomLength: Int
  RoomMasterBedroomLevel: String
  RoomMasterBedroomWidth: Int
  RoomBedroom1Dimensions: String
  MFR_room3_RoomFlooring: String
  RoomBedroom1Length: Int
  RoomBedroom1Level: String
  RoomBedroom1Width: Int
  RoomLivingRoomDimensions: String
  MFR_room4_RoomFlooring: String
  RoomLivingRoomLength: Int
  RoomLivingRoomLevel: String
  RoomLivingRoomWidth: Int
  RoomDiningRoomDimensions: String
  MFR_room5_RoomFlooring: String
  RoomDiningRoomLength: Int
  RoomDiningRoomLevel: String
  RoomDiningRoomWidth: Int
  MlgCanView: Boolean
  ModificationTimestamp: String
}

input PropertyInput {
  propertyId: String
  MFR_AdditionalLeaseRestrictions: String
  AdditionalParcelsYN: Boolean
  Appliances: String
  MFR_ApprovalProcess: String
  ArchitecturalStyle: String
  AssociationAmenities: String
  MFR_AssociationApprovalRequiredYN: String
  MFR_AssociationEmail: String
  AssociationFee: Float
  AssociationFeeFrequency: String
  AssociationFeeIncludes: String
  MFR_AssociationFeeRequirement: String
  MFR_AssociationURL: String
  AssociationYN: Boolean
  AttachedGarageYN: Boolean
  MFR_AvailableForLeaseYN: String
  BathroomsFull: Int
  BathroomsHalf: Int
  BathroomsTotalInteger: Int
  BedroomsTotal: Int
  MFR_BuildingNameNumber: String
  BuyerAgencyCompensation: String
  CarportYN: Boolean
  MFR_CDDYN: String
  City: String
  CoListAgentDirectPhone: String
  CoListAgentFullName: String
  CoListAgentMlsId: String
  CoListOfficeMlsId: String
  CoListOfficeName: String
  CommunityFeatures: String
  ConstructionMaterials: String
  Cooling: String
  Country: String
  CountyOrParish: String
  CumulativeDaysOnMarket: Int
  MFR_CurrentPrice: String
  DaysOnMarket: Int
  DirectionFaces: String
  Directions: String
  ElementarySchool: String
  MFR_EndDateofLease: String
  MFR_ExistLseTenantYN: String
  ExteriorFeatures: String
  FireplaceYN: Boolean
  MFR_FloodZoneCode: String
  Flooring: String
  FoundationDetails: String
  MFR_GarageDimensions: String
  GarageSpaces: Int
  GarageYN: Boolean
  MFR_GreenVerificationCount: String
  Heating: String
  HighSchool: String
  MFR_HomesteadYN: String
  InteriorFeatures: String
  InternetAddressDisplayYN: Boolean
  InternetConsumerCommentYN: Boolean
  InternetEntireListingDisplayYN: Boolean
  Latitude: Float
  Levels: String
  ListAgentAOR: String
  ListAgentDirectPhone: String
  ListAgentEmail: String
  ListAgentFullName: String
  ListAgentKey: String
  ListAgentMlsId: String
  ListAgentPager: String
  ListAOR: String
  ListingAgreement: String
  ListingContractDate: String
  ListingId: String
  ListingKey: String
  OriginatingSystemKey: String
  ListingTerms: String
  MFR_ListOfficeHeadOfficeKeyNumeric: String
  ListOfficeKey: String
  ListOfficeMlsId: String
  ListOfficeName: String
  ListOfficePhone: String
  ListPrice: Int
  LivingArea: Int
  MFR_LivingAreaMeters: String
  Longitude: Float
  LotFeatures: String
  LotSizeAcres: Float
  LotSizeSquareFeet: Int
  MFR_LotSizeSquareMeters: String
  MiddleOrJuniorSchool: String
  MFR_MinimumLease: String
  MLSAreaMajor: String
  MlsStatus: String
  OriginatingSystemModificationTimestamp: String
  MFR_MonthlyHOAAmount: String
  NewConstructionYN: Boolean
  MFR_NonRepCompensation: String
  OriginalEntryTimestamp: String
  OriginalListPrice: Int
  OriginatingSystemName: String
  ParcelNumber: String
  ParkingFeatures: String
  MFR_PetRestrictions: String
  PetsAllowed: String
  PhotosChangeTimestamp: String
  PhotosCount: Int
  PoolPrivateYN: Boolean
  PostalCode: String
  PostalCodePlus4: String
  PrivateRemarks: String
  PropertySubType: String
  PropertyType: String
  PublicRemarks: String
  MFR_PublicRemarksAgent: String
  PublicSurveyRange: String
  PublicSurveySection: String
  MFR_RealtorInfo: String
  Roof: String
  MFR_RoomCount: String
  MFR_SDEOYN: String
  SeniorCommunityYN: Boolean
  Sewer: String
  ShowingRequirements: String
  SpecialListingConditions: String
  StandardStatus: String
  StateOrProvince: String
  StatusChangeTimestamp: String
  StoriesTotal: Int
  StreetName: String
  StreetNumber: String
  StreetSuffix: String
  SubdivisionName: String
  TaxAnnualAmount: Float
  TaxBlock: String
  TaxBookNumber: String
  TaxLegalDescription: String
  TaxLot: String
  TaxYear: Int
  MFR_TotalAcreage: String
  MFR_TotalAnnualFees: String
  MFR_TotalMonthlyFees: String
  Township: String
  TransactionBrokerCompensation: String
  MFR_UniversalPropertyID: String
  UnparsedAddress: String
  Utilities: String
  View: String
  MFR_WaterAccessYN: String
  MFR_WaterExtrasYN: String
  MFR_WaterfrontFeetTotal: String
  WaterfrontYN: Boolean
  WaterSource: String
  MFR_WaterView: String
  MFR_WaterViewYN: String
  WindowFeatures: String
  YearBuilt: Int
  MFR_YrsOfOwnerPriorToLeasingReqYN: String
  Zoning: String
  RoomKitchenDimensions: String
  RoomKitchenFeatures: String
  MFR_room1_RoomFlooring: String
  RoomKitchenLength: Int
  RoomKitchenLevel: String
  RoomType: String
  RoomKitchenWidth: Int
  RoomMasterBedroomDimensions: String
  MFR_room2_RoomFlooring: String
  RoomMasterBedroomLength: Int
  RoomMasterBedroomLevel: String
  RoomMasterBedroomWidth: Int
  RoomBedroom1Dimensions: String
  MFR_room3_RoomFlooring: String
  RoomBedroom1Length: Int
  RoomBedroom1Level: String
  RoomBedroom1Width: Int
  RoomLivingRoomDimensions: String
  MFR_room4_RoomFlooring: String
  RoomLivingRoomLength: Int
  RoomLivingRoomLevel: String
  RoomLivingRoomWidth: Int
  RoomDiningRoomDimensions: String
  MFR_room5_RoomFlooring: String
  RoomDiningRoomLength: Int
  RoomDiningRoomLevel: String
  RoomDiningRoomWidth: Int
  MlgCanView: Boolean
  ModificationTimestamp: String
}

type Query {
  allProperties: [Property!]! @index(name: "all_properties")
  propertyByPropertyId(propertyId: String!): Property
}

type Mutation {
  upsertProperties(properties: [PropertyInput!]!): [Property]! @resolver(name: "upsert_properties")
}